version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - aws configure list
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - |
        aws cloudformation package \
          --template-file template.yml \
          --s3-bucket cc.hiroga.cfn \
          --output-template-file output-template.yml \
          --region ap-northeast-1
  post_build:
    commands:
      - |
        aws cloudformation deploy \
          --template-file output-template.yml \
          --stack-name ktor-lambbda \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
          --region ap-northeast-1

artifacts:
  type: zip
  files:
    - target/messageUtil-1.0.jar